Import and read CSV file

In [175]:
# importing the depencies
import pandas as pd

In [176]:
# read CSV file
df_csv = pd.read_csv("Files/people.csv")
# the dataframe will be truncated by 5 from the top and 5 from the bottom
df_csv

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon
...,...,...,...,...,...,...,...,...,...
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [177]:
# print entire dataframe
print(df_csv.to_string())

    Index          User Id  First Name   Last Name     Sex                         Email                   Phone Date of birth                                                    Job Title
0       1  88F7B33d2bcf9f5      Shelby     Terrell    Male          elijah57@example.net  001-084-906-7849x73518    1945-10-26                                              Games developer
1       2  f90cD3E76f1A9b9     Phillip     Summers  Female         bethany14@example.com       214.112.6044x4913    1910-03-24                                               Phytotherapist
2       3  DbeAb8CcdfeFC2c    Kristine      Travis    Male         bthompson@example.com            277.609.7938    1992-07-02                                                    Homeopath
3       4  A31Bee3c201ef58     Yesenia    Martinez    Male     kaitlinkaiser@example.com            584.094.6111    2017-08-03                                            Market researcher
4       5  1bA7A3dc874da3c        Lori        Todd    Male    buchananmanuel@example.net       689-207-3558x7233    1938-12-01                                           Veterinary surgeon
5       6  bfDD7CDEF5D865B        Erin         Day    Male           tconner@example.org   001-171-649-9856x5553    2015-10-28                                     Waste management officer
6       7  bE9EEf34cB72AF7   Katherine        Buck  Female       conniecowan@example.com   +1-773-151-6685x49162    1989-01-22                                         Intelligence analyst
7       8  2EFC6A4e77FaEaC     Ricardo      Hinton    Male       wyattbishop@example.com  001-447-699-7998x88612    1924-03-26                                               Hydrogeologist
8       9  baDcC4DeefD8dEB        Dave     Farrell    Male           nmccann@example.net      603-428-2429x27392    2018-10-06                                                       Lawyer
9      10  8e4FB470FE19bF0      Isaiah       Downs    Male   virginiaterrell@example.org    +1-511-372-1544x8206    1964-09-20                                               Engineer, site
10     11  BF0BbA03C29Bb3b      Sheila        Ross  Female        huangcathy@example.com            895.881.4746    2008-03-20                                Advertising account executive
11     12  F738c69fB34E62E       Stacy      Newton    Male          rayleroy@example.org      710.673.3213x80335    1980-10-20                                                Warden/ranger
12     13  C03fDADdAadAdCe       Mandy       Blake    Male      jefferynoble@example.org      (992)466-1305x4947    2007-12-08                                          Scientist, clinical
13     14  b759b74BD1dE80d     Bridget        Nash  Female        mercedes44@example.com           (216)627-8359    2004-06-28                                                Social worker
14     15  1F0B7D65A00DAF9     Crystal      Farmer    Male          pmiranda@example.org         +1-024-377-5391    1992-03-09                                      Agricultural consultant
15     16  50Bb061cB30B461      Thomas      Knight  Female    braunpriscilla@example.net         +1-360-880-0766    2006-02-18                              Sport and exercise psychologist
16     17  D6dbA5308fEC4BC     Maurice      Rangel    Male       sheenabanks@example.com           (246)187-4969    2004-08-20                                      Secretary/administrator
17     18  311D775990f066d       Frank     Meadows    Male           gbrewer@example.org       429.965.3902x4447    2008-09-16                                       Audiological scientist
18     19  7F7E1BAcb0C9AFf       Alvin        Paul    Male  gilbertdonaldson@example.com      219.436.0887x07551    1949-05-12                                     Teacher, adult education
19     20  88473e15D5c3cD0       Jared    Mitchell  Female           jcortez@example.com         +1-958-849-6781    1921-01-18                                             Paediatric nurse
20     21  b31D271F8c200AB  Jacqueline      Norton  Female            carias@example.net      819.309.7679x59173    1952-10-09                                            Scientist, marine
21     22  42F4BdA841aBadC     Colleen    Hatfield  Female             fknox@example.org            638.584.1090    1949-10-14                                    Commercial horticulturist
22     23  cBbBcA0FCA3C4Bc       Randy      Barnes    Male         huangbill@example.org  001-960-629-7164x67214    1947-12-30                         Outdoor activities/education manager
23     24  f1f89173353aD90      Janice      Rhodes  Female   juarezdominique@example.net   001-249-314-9742x6996    1999-11-01                                            Drilling engineer
24     25  c5B09fb33e8bA0A      Alfred      Mcneil  Female   cassandramorris@example.com     (468)276-9509x53058    1993-05-28                                              Systems analyst
25     26  c9F2282C40BEC1E        Sean      Levine    Male       sallymiller@example.net              4915828504    2010-10-09                                 Conservation officer, nature
26     27  9c1bc7EC53Fb7cE       Louis       Payne    Male         bsullivan@example.net              6232695307    1916-01-29                                                   Counsellor
27     28  ddEc50e2A2e3a2B    Brittney        Vega  Female         ayalajose@example.net            945-739-8686    1932-10-31                                            Recycling officer
28     29  66F096D36Ebae11        Judy     Buckley    Male          irosales@example.net  001-654-208-1241x52830    1963-07-28                                          Art gallery manager
29     30  F0fE2faAd78F8b5      Norman       Weber    Male           mconrad@example.com            223.002.0429    1957-05-21                                                       Gaffer
30     31  5d2feAfbdCAA6B5      Isaiah     Camacho  Female          jimblake@example.org        001-536-544-3367    1966-04-07                                            Food technologist
31     32  cDa5F303fCd6dEa  Jacqueline   Gallagher    Male          nsampson@example.net           (247)762-8934    1999-02-25                                   Building services engineer
32     33  8Ef7DBfcaB02b6B      Bonnie     Andrews  Female         caitlin24@example.net    +1-253-987-2776x9161    1953-12-21                                          Seismic interpreter
33     34  6Dec5b5542F8ed8     Brandon     Schmidt  Female           mconley@example.net     +1-386-673-1465x006    1931-05-12                                         Engineer, biomedical
34     35  3Fb8a7f68e12784     Jackson      Sparks  Female    reynoldsdarryl@example.net     (137)908-3129x65035    1980-11-18                                                 Set designer
35     36  035eff50B9A0F24      Melody        Cook    Male         jeannovak@example.org           (826)792-7381    1963-06-25                           Research scientist (life sciences)
36     37  aa614aAE4B7Cf0C     Leonard       Hurst    Male         clinton78@example.org      941-038-0427x38800    1938-03-13                             Accountant, chartered management
37     38  ACcde95AAe3e6cC        Gene        Rich  Female        luisdeleon@example.org   +1-356-818-6604x89537    1946-08-22                                           Surveyor, quantity
38     39  b6a35de5CB6fc25     Cynthia     Wiggins  Female       rosariodave@example.org     (110)858-2437x70190    1984-01-27                         Outdoor activities/education manager
39     40  e92A191E345fA3A       Tanya    Mckinney  Female      vickihouston@example.com       (830)774-9002x086    2003-03-12                                  Information systems manager
40     41  7D0AcBF6CCac3fd     Matthew       Stone  Female          evelyn31@example.org            952-381-6360    2017-08-23  Scientist, clinical (histocompatibility and immunogenetics)
41     42  CEFA7BBCef013AE        Kirk       Walsh  Female     stephenfuller@example.org   001-826-496-5529x8661    2009-04-08                                        Accounting technician
42     43  9edBC94aE7cA22a      Willie        Vang  Female      haleymathews@example.net        741.168.6854x067    1978-02-02                                        Management consultant
43     44  fFe7BAA737aDbe2      Miguel        Hill  Female          tyrone56@example.org              5247842945    1930-08-26                                                         Make
44     45  5F2f3fAca8B0946      Darren     Andrews    Male        lhernandez@example.com           (975)799-4261    1997-10-04                                                Retail banker
45     46  6bFcfc3cc1BC6B4       Haley        Pugh  Female           molly03@example.org      (746)182-6137x2453    1980-09-16                                         Commissioning editor
46     47  f3BD2cBF7eEb6df    Danielle     Estrada  Female             jvang@example.org       (890)374-9518x772    1930-07-09                             Accountant, chartered management
47     48  Ee4eB129dC7913A       Becky       Brady    Male       erikmueller@example.org           (390)002-0863    1957-06-27                                          Seismic interpreter
48     49  dBCEf340C3657Eb     Caitlyn        Frey    Male    rivasdominique@example.org      805-021-3965x46344    1968-01-26                                           Jewellery designer
49     50  E47FB71DD9ACCd9      Joshua     Sweeney    Male        daisymcgee@example.net        875.994.2100x535    1954-07-28                                    Education officer, museum
50     51  eA3fDd79BE9f0E7       Heidi     Escobar  Female    staffordtravis@example.net       601-155-3065x1131    1931-09-25                                    Estate manager/land agent
51     52  aF0eE4547Bc025c       Brian    Oconnell  Female          saralong@example.net        952-283-1423x733    1911-10-23                                              Physiotherapist
52     53  9F5DeD7aD228F5a     Beverly     Esparza  Female           iphelps@example.net    +1-327-578-8754x6771    1930-12-09                                  Passenger transport manager
53     54  D3Fa0220dDE4d36   Nathaniel       Rivas  Female         roberto29@example.com     (655)887-2040x37888    1908-11-17                                          Call centre manager
54     55  60FdBFd5e7BE8fF       Debra       Payne  Female         yolanda07@example.org  001-731-525-8400x52593    1927-08-20                            Special educational needs teacher
55     56  D8bF5Ab2b98caff   Mackenzie       Rocha  Female      abbottyvette@example.net              4225525458    1980-10-21                           Museum/gallery exhibitions officer
56     57  CD8d33aA25bc8BB    Courtney     Watkins  Female            ochang@example.org       210.683.2761x5883    2003-12-07                                       Pension scheme manager
57     58  Fac3BfFf0A3d03c        Fred       Olsen  Female       amyanderson@example.com            497-774-3053    1910-04-10                                                Archaeologist
58     59  e552D7ddafe1FFb        Ryan      Nelson  Female           qnorman@example.org            956.330.2951    1924-05-02            Historic buildings inspector/conservation officer
59     60  0f8deedb629A5f6       Grace      Phelps    Male      clarkeangela@example.net      (034)867-8827x6777    1909-10-15                                           Petroleum engineer
60     61  bB9e49E506F65ed       Shari   Daugherty    Male         kalvarado@example.org   001-951-655-4798x6124    1944-11-24                                                      Curator
61     62  Ed724605A403D91       Kelli      Garner    Male       jodyvincent@example.org       995.000.4213x0982    2010-01-17                                                Retail banker
62     63  0aBE5ACb18E0c10      Jackie     Bennett    Male    hutchinsonkirk@example.com   001-740-937-0846x0087    1915-11-11                                                 Neurosurgeon
63     64  5D2cb63CaAF53f6      Leslie      Conway  Female   floreschristina@example.org        795.782.4384x555    1983-11-06                                                 Chiropractor
64     65  Ee6974f90eeCe18      Harold     Barnett  Female          nathan65@example.org         +1-026-265-6392    1943-03-15                                         Biochemist, clinical
65     66  cEf02C076afa07f       Larry      Harper    Male           maria32@example.org    +1-244-630-3792x4121    2021-05-05                                     Scientist, water quality
66     67  9Df5Ba591bF3EFf        Mike        Ward  Female       imccullough@example.com            116-729-5046    1967-11-09                                                  Hydrologist
67     68  3faB1CBfEFBDdD4    Brittney       Rubio  Female           corey92@example.com            593.976.2528    1959-12-24                                         Biochemist, clinical
68     69  Ebcefdf75eCb0a9       Frank      Pineda    Male      daltoncalvin@example.net      (035)961-5060x9182    1926-03-10                                          Hospital pharmacist
69     70  e75e5DBfcb68887      Sandra          Wu    Male            ubanks@example.com     +1-096-606-6454x067    1925-04-28                                            Warehouse manager
70     71  6a53a8D41dDF6de        Ryan      Benton    Male       lopezdebbie@example.org     +1-695-557-9948x485    2020-10-06                                      Physiological scientist
71     72  F0d3bD1aaf9E3Bc      Tamara        Hull    Male          meagan39@example.net       017.665.3744x7944    1933-01-31                         English as a second language teacher
72     73  5bC87340799FBD0        Jean      Ritter  Female        kristina76@example.com           (954)060-1066    1985-08-06                                             Financial trader
73     74  dBfA17Aaf16b4ab    Veronica      Briggs  Female      weissbridget@example.com   +1-521-589-2387x48490    1974-06-08                                          Structural engineer
74     75  c935b7Eb6FA0B0F         Kim     Andrews  Female         wpetersen@example.org              7677125383    1990-11-15                                         Biochemist, clinical
75     76  b3e15e65Ca2CcBf        Tina  Cunningham    Male          wongmary@example.org            079-907-5051    1956-11-29                                       Race relations officer
76     77  dade3452F0c32FD    Jonathon    Atkinson    Male        gailfrench@example.net        874-037-2032x932    2011-07-19                                       Psychologist, forensic
77     78  AdEd6cfD85DeC46    Jermaine        Reid  Female             vpaul@example.com           (742)214-8691    1974-08-18                                         Newspaper journalist
78     79  DAf111987098ae4      Regina     Stevens    Male            xpoole@example.net            891-359-2684    2011-11-28                                         Public house manager
79     80  6e6a5b885F6496d    Terrence        Huff    Male       cassandra80@example.org       221.800.6408x5416    1944-02-27                                  Careers information officer
80     81  12DCb4ED8E01D5C       Tyler       Foley  Female       johnathan72@example.org   001-386-469-3075x8030    1908-09-19                                                    Economist
81     82  E1cB5cA8CA7CC0a      Andrew      Waters    Male             nhall@example.net    +1-376-865-2765x3351    1948-05-14                                           Jewellery designer
82     83  AedDfaE8Cf49F07    Reginald  Stephenson    Male         erikaball@example.net     +1-832-500-6044x475    2010-02-08                                   Contracting civil engineer
83     84  bff9853aFAeF772     Douglas       Reese  Female      nixonvanessa@example.net   001-834-660-8312x9864    1961-11-11                                    Higher education lecturer
84     85  E883773cA5219Be       Helen  Williamson  Female          melvin08@example.net        001-377-726-4229    1911-08-11                                  Lecturer, further education
85     86  CB19EafEbBfF9eC       Mario      Vaughn    Male            oblake@example.com      160-144-5039x12276    1990-07-08                           Research scientist (life sciences)
86     87  5834700fbEd2771     Chelsea     Dickson    Male   johnnyhendricks@example.net  001-698-651-0138x18588    1958-05-13                                     Teacher, early years/pre
87     88  2b0Ab1Dc9E01D7E      Dustin      Bailey    Male           pbarron@example.net     +1-965-621-1157x345    1908-08-22                                        Travel agency manager
88     89  3f3a3D89ad042Dd       Harry      Medina  Female        olsenmalik@example.net         +1-451-099-5805    1947-08-24                                     Technical sales engineer
89     90  9425E2F38C408ef       Kathy       Haney  Female          teresa37@example.com           (164)105-8456    1955-09-02                                           Charity fundraiser
90     91  F0aeC9c2759F3C6      Alison       Nixon  Female            zmiles@example.net              3506680871    1941-07-10                                              Patent attorney
91     92  d6EA619A7C4aA95       Jamie       Hardy  Female     sheenadouglas@example.com     (900)803-9295x11533    1994-07-17                                       Conservator, furniture
92     93  2A33E7Cad1bb0F5      Melody         Cox  Female            evan90@example.org      (626)520-5080x3511    1974-07-30                               Dance movement psychotherapist
93     94  d181FFB7d3E68bb      Xavier        Cole    Male         nicolas90@example.org              8164259975    1938-11-29                                            Financial planner
94     95  feaBf8dAE0C0d6F      Dillon      Guzman  Female     angelanavarro@example.net            971-992-4521    1942-04-01                                                   Air broker
95     96  5eFda7caAeB260E      Dennis      Barnes  Female           bmartin@example.org    001-095-524-2112x257    1954-07-30                                            Software engineer
96     97  CCbFce93d3720bE       Steve   Patterson  Female         latasha46@example.net        001-865-478-5157    1932-04-29                                                    Barrister
97     98  2fEc528aFAF0b69      Wesley        Bray    Male          regina11@example.org      995-542-3004x76800    1994-12-28                                               Police officer
98     99  Adc7ad9B6e4A1Fe      Summer    Oconnell  Female    alexiscantrell@example.org    001-273-685-6932x092    2012-04-12                                         Broadcast journalist
99    100  b8D0aD3490FC7e1      Mariah     Bernard    Male         pcopeland@example.org     (341)594-6554x44657    2016-11-15                                        IT sales professional

In [178]:
# print 5 data frames from top
df_csv.head(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [179]:
# print 5 data frames from bottom
df_csv.tail(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [180]:
# find specific gender (Male)
male = df_csv[df_csv["Sex"] == "Male"]
male.head(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon
5,6,bfDD7CDEF5D865B,Erin,Day,Male,tconner@example.org,001-171-649-9856x5553,2015-10-28,Waste management officer

In [ ]:
# number of data (male)
print(f"DataFrame size = {male.shape}")
print(f"Number of Male = {male.shape[0]}")

Number of data = (47, 9)
Number of Male = 47

In [182]:
# find specific gender (Female)
female = df_csv[df_csv["Sex"] ==  "Female"]
female.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
6,7,bE9EEf34cB72AF7,Katherine,Buck,Female,conniecowan@example.com,+1-773-151-6685x49162,1989-01-22,Intelligence analyst
10,11,BF0BbA03C29Bb3b,Sheila,Ross,Female,huangcathy@example.com,895.881.4746,2008-03-20,Advertising account executive
13,14,b759b74BD1dE80d,Bridget,Nash,Female,mercedes44@example.com,(216)627-8359,2004-06-28,Social worker
15,16,50Bb061cB30B461,Thomas,Knight,Female,braunpriscilla@example.net,+1-360-880-0766,2006-02-18,Sport and exercise psychologist

In [ ]:
# number od data (female)
print(f"DataFrame size = {female.shape}")
print(f"Number of Female = {female.shape[0]}")

Number of data = (53, 9)
Number of Female = 53

In [184]:
# find poeple who born above 1999
teenagers = df_csv[df_csv["Date of birth"] > "1999-12-31"]
teenagers.head(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
5,6,bfDD7CDEF5D865B,Erin,Day,Male,tconner@example.org,001-171-649-9856x5553,2015-10-28,Waste management officer
8,9,baDcC4DeefD8dEB,Dave,Farrell,Male,nmccann@example.net,603-428-2429x27392,2018-10-06,Lawyer
10,11,BF0BbA03C29Bb3b,Sheila,Ross,Female,huangcathy@example.com,895.881.4746,2008-03-20,Advertising account executive
12,13,C03fDADdAadAdCe,Mandy,Blake,Male,jefferynoble@example.org,(992)466-1305x4947,2007-12-08,"Scientist, clinical"

In [ ]:
# number of data (date of birth > 1999-12-31)
print(f"DataFrame size = {teenagers.shape}")
print(f"Number of People born above 1999-12-31 = {teenagers.shape[0]}")

Number of data = (22, 9)
Number of People born above 1999-12-31 = 22

Import and read Json file

In [186]:
# read a json file
df_json = pd.read_json("Files/people.json")
# the dataframe will be truncated by 5 from the top and 5 from the bottom
df_json

,name,language,id,bio,version
0,Adeel Solangi,Sindhi,V59OF92YF627HFY0,Donec lobortis eleifend condimentum. Cras dict...,6.10
1,Afzal Ghaffar,Sindhi,ENTOCR13RSCLZ6KU,"Aliquam sollicitudin ante ligula, eget malesua...",1.88
2,Aamir Solangi,Sindhi,IAKPO3R4761JDRVG,Vestibulum pharetra libero et velit gravida eu...,7.27
3,Abla Dilmurat,Uyghur,5ZVOEPMJUI4MB4EN,Donec lobortis eleifend condimentum. Morbi ac ...,2.53
4,Adil Eli,Uyghur,6VTI8X6LL0MMPJCC,"Vivamus id faucibus velit, id posuere leo. Mor...",6.49
...,...,...,...,...,...
192,Kristín Sigurðardóttir,Icelandic,ZP5TBBYX6RI2UJ31,Cras dictum dolor lacinia lectus vehicula rutr...,2.80
193,Rohini Vasav,Hindi,UEFML43TCGS04KWM,"Ut accumsan, est vel fringilla varius, purus a...",9.30
194,Sunil Kapoor,Hindi,VY2A0APGVHK5NAW2,"Proin tempus eu risus nec mattis. Ut dictum, l...",8.04
195,Zamokuhle Zulu,isiZulu,XU7BX2F8M5PVZ1EF,Etiam congue dignissim volutpat. Phasellus tin...,8.39
196,Bhupesh Menon,Hindi,0CEPNRDV98KT3ORP,Maecenas tempus neque ut porttitor malesuada. ...,2.69

In [187]:
# show entire dataframe
print(df_json.to_string())

                       name          language                id                                                                                                                                                                                                                                                                                                                                                                                                bio  version
0             Adeel Solangi            Sindhi  V59OF92YF627HFY0                                                                                                                                                                                                                   Donec lobortis eleifend condimentum. Cras dictum dolor lacinia lectus vehicula rutrum. Maecenas quis nisi nunc. Nam tristique feugiat est vitae mollis. Maecenas quis nisi nunc.     6.10
1             Afzal Ghaffar            Sindhi  ENTOCR13RSCLZ6KU                                                                                                                                                                Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Etiam congue dignissim volutpat. Vestibulum pharetra libero et velit gravida euismod.     1.88
2             Aamir Solangi            Sindhi  IAKPO3R4761JDRVG                                                                                                                                                                                                                             Vestibulum pharetra libero et velit gravida euismod. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Fusce eu ultrices elit, vel posuere neque.     7.27
3             Abla Dilmurat            Uyghur  5ZVOEPMJUI4MB4EN                                                                                                                                                                                                                                                                                                                                         Donec lobortis eleifend condimentum. Morbi ac tellus erat.     2.53
4                  Adil Eli            Uyghur  6VTI8X6LL0MMPJCC                                                                                                                                                                                                                                                                         Vivamus id faucibus velit, id posuere leo. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Suspendisse potenti.     6.49
5               Adile Qadir            Uyghur  F2KEU5L7EHYSYFTT                                                                                                                                                                                                                  Duis commodo orci ut dolor iaculis facilisis. Morbi ultricies consequat ligula posuere eleifend. Aenean finibus in tortor vel aliquet. Fusce eu ultrices elit, vel posuere neque.     1.90
6         Abdukerim Ibrahim            Uyghur  LO6DVTZLRK68528I                                                                                                                                                                                                                                          Vivamus id faucibus velit, id posuere leo. Nunc aliquet sodales nunc a pulvinar. Nunc aliquet sodales nunc a pulvinar. Ut viverra quis eros eu tincidunt.     5.90
7                 Adil Abro            Sindhi  LJRIULRNJFCNZJAJ                                                     Etiam malesuada blandit erat, nec ultricies leo maximus sed. Fusce congue aliquam elit ut luctus. Etiam malesuada blandit erat, nec ultricies leo maximus sed. Cras dictum dolor lacinia lectus vehicula rutrum. Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero.     9.32
8          Afonso Vilarchán          Galician  JMCL0CXNXHPL1GBC                                                                                                                                                                                                                                                                                                   Fusce eu ultrices elit, vel posuere neque. Morbi ac tellus erat. Nunc tincidunt laoreet laoreet.     5.21
9             Mark Schembri           Maltese  KU4T500C830697CW                               Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. Morbi ultricies consequat ligula posuere eleifend. Vivamus id faucibus velit, id posuere leo. Sed laoreet posuere sapien, ut feugiat nibh gravida at. Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros.     3.17
10            Antía Sixirei          Galician  XOF91ZR7MHV1TXRS                                                                                                         Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Morbi finibus dui sed est fringilla ornare. Duis pellentesque ultrices convallis. Morbi ultricies consequat ligula posuere eleifend.     6.44
11           Aygul Mutellip            Uyghur  FTSNV411G5MKLPDT                                                                                                                                                        Duis commodo orci ut dolor iaculis facilisis. Nam semper gravida nunc, sit amet elementum ipsum. Donec pellentesque ultrices mi, non consectetur eros luctus non. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna.     9.10
12             Awais Shaikh            Sindhi  OJMWMEEQWMLDU29P                                                                                                                  Nunc aliquet sodales nunc a pulvinar. Ut dictum, ligula eget sagittis maximus, tellus mi varius ex, a accumsan justo tellus vitae leo. Donec pellentesque ultrices mi, non consectetur eros luctus non. Nulla finibus massa at viverra facilisis. Nunc tincidunt laoreet laoreet.     1.59
13            Ambreen Ahmed            Sindhi  5G646V7E6TJW8X2M                                                                                                                                        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros.     2.35
14              Celtia Anes          Galician  Z53AJY7WUYPLAWC9                                                                                                                                                                                                                                                                Nullam ac sodales dolor, eu facilisis dui. Maecenas non arcu nulla. Ut viverra quis eros eu tincidunt. Curabitur quis commodo quam.     8.34
15            George Mifsud           Maltese  N1AS6UFULO6WGTLB                                                                              Phasellus tincidunt sollicitudin posuere. Ut accumsan, est vel fringilla varius, purus augue blandit nisl, eu rhoncus ligula purus vel dolor. Donec congue sapien vel euismod interdum. Cras dictum dolor lacinia lectus vehicula rutrum. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula.     7.47
16             Aytürk Qasim            Uyghur  70RODUVRD95CLOJL                                                                                                                                                                                                                                          Curabitur ultricies id urna nec ultrices. Aliquam scelerisque pretium tellus, sed accumsan est ultrices id. Duis commodo orci ut dolor iaculis facilisis.     1.32
17               Dialè Meso  Sesotho sa Leboa  VBLI24FKF7VV6BWE                                                                                                                                                                                                                                                      Maecenas non arcu nulla. Vivamus id faucibus velit, id posuere leo. Nullam sodales convallis mauris, sit amet lobortis magna auctor sit amet.     6.29
18            Breixo Galáns          Galician  4VRLON0GPEZYFCVL                                                                                  Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero. Morbi ac tellus erat. In id elit malesuada, pulvinar mi eu, imperdiet nulla. Vestibulum pharetra libero et velit gravida euismod. Cras dictum dolor lacinia lectus vehicula rutrum.     1.62
19             Bieito Lorme          Galician  5DRDI1QLRGLP29RC                                                                                                                                                                                                                                                   Ut viverra quis eros eu tincidunt. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Curabitur quis commodo quam. Morbi ac tellus erat.     4.45
20            Azrugul Osman            Uyghur  5RCTVD3C5QGVAKTQ                                                                                                                                                                                                                                                                                                                 Maecenas tempus neque ut porttitor malesuada. Donec lobortis eleifend condimentum.     3.18
21           Brais Verdiñas          Galician  BT407GHCC0IHXCD3                                                                                                                                                                  Quisque maximus sodales mauris ut elementum. Ut viverra quis eros eu tincidunt. Sed eu libero maximus nunc lacinia lobortis et sit amet nisi. In id elit malesuada, pulvinar mi eu, imperdiet nulla. Curabitur quis commodo quam.     5.01
22              Ekber Sadir            Uyghur  AGZDAP8D8OVRRLTY                                                               Quisque efficitur vel sapien ut imperdiet. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. In id elit malesuada, pulvinar mi eu, imperdiet nulla. Sed nec suscipit ligula. Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero.     2.04
23           Doreen Bartolo           Maltese  59QSX02O2XOZGRLH                                                                                                        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Nam semper gravida nunc, sit amet elementum ipsum. Ut viverra quis eros eu tincidunt. Curabitur sed condimentum felis, ut luctus eros.     9.31
24                 Ali Ayaz            Sindhi  3WNLUZ5LT2F7MYVU                                                                                                                                Cras dictum dolor lacinia lectus vehicula rutrum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Etiam malesuada blandit erat, nec ultricies leo maximus sed.     7.80
25           Guzelnur Polat            Uyghur  I6QQHAEGV4CYDXLP                                                                                             Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam consequat enim lorem, at tincidunt velit ultricies et. Nulla finibus massa at viverra facilisis.     8.56
26              John Falzon           Maltese  U3AWXHDTSU0H82SL                                                                                                                                                                                                                                                                                                 Sed nec suscipit ligula. Nullam sodales convallis mauris, sit amet lobortis magna auctor sit amet.     9.96
27              Erkin Qadir            Uyghur  GV6TA1AATZYBJ3VR                                                                                                                                                                                                                                                                                                                      Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. .     3.53
28             Anita Rajput            Sindhi  XLLVD0NO2ZFEP4AK                                                                                                                                                                                                                                                                                                                Nam semper gravida nunc, sit amet elementum ipsum. Etiam congue dignissim volutpat.     5.16
29          Ayesha Khalique            Sindhi  Q9A5QNGA0OSU8P6Y                                                                                                                                                                                                                                                                    Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Etiam mauris magna, fermentum vitae aliquet eu, cursus vitae sapien.     3.90
30          Pheladi Rammala  Sesotho sa Leboa  EELSIRT2T4Q0M3M4                                                                                                                                                          Quisque efficitur vel sapien ut imperdiet. Morbi ac tellus erat. Aliquam scelerisque pretium tellus, sed accumsan est ultrices id. Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros.     1.88
31            Antón Caneiro          Galician  ENTAPNU3MMFUGM1W                                                                                                                                                                                                                 Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero. Vestibulum pharetra libero et velit gravida euismod.     4.84
32            Qahar Abdulla            Uyghur  OGLODUPEHKEW0K83                                                                  Duis commodo orci ut dolor iaculis facilisis. Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Fusce congue aliquam elit ut luctus. Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero. Quisque maximus sodales mauris ut elementum.     3.65
33             Reyhan Murat            Uyghur  Y91F4D54794E9ANT                                                                                                                                                                                                                                                                                                             Suspendisse sit amet ullamcorper sem. Curabitur sed condimentum felis, ut luctus eros.     2.69
34           Tatapi Phogole  Sesotho sa Leboa  7JA42P5CMCWDVPNR                                                                                                                                                                                                                   Duis luctus, lacus eu aliquet convallis, purus elit malesuada ex, vitae rutrum ipsum dui ut magna. Nullam ac sodales dolor, eu facilisis dui. Ut viverra quis eros eu tincidunt.     3.78
35           Marcos Amboade          Galician  WPX7H97C7D70CZJR                                                                                         Nulla finibus massa at viverra facilisis. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Curabitur ultricies id urna nec ultrices. Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros. Nunc aliquet sodales nunc a pulvinar.     7.37
36             Grace Tabone           Maltese  K4XO8G8DMRNSHF2B                                                                                                                                                                                                                                                Curabitur sed condimentum felis, ut luctus eros. Duis luctus, lacus eu aliquet convallis, purus elit malesuada ex, vitae rutrum ipsum dui ut magna.     5.36
37            Shafqat Memon            Sindhi  D8VFLVRXBXMVBRVI                                                                                                                                                                               Aliquam scelerisque pretium tellus, sed accumsan est ultrices id. . Curabitur quis commodo quam. Quisque maximus sodales mauris ut elementum. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex.     8.95
38             Zeynep Semet            Uyghur  Z324TZV8S0FGDSAO                                                                                                                                                                                                                                        Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Fusce eu ultrices elit, vel posuere neque. Nulla finibus massa at viverra facilisis.     1.03
39              Meladi Papo  Sesotho sa Leboa  RJAZQ6BBLRT72CD9                                                                                                Quisque efficitur vel sapien ut imperdiet. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Ut accumsan, est vel fringilla varius, purus augue blandit nisl, eu rhoncus ligula purus vel dolor. Etiam congue dignissim volutpat. Donec congue sapien vel euismod interdum.     7.22
40               Semet Alim            Uyghur  HI7L2SR4RCS8C8CS                                                                                                                                                                                                                                                          Duis commodo orci ut dolor iaculis facilisis. Ut viverra quis eros eu tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit.     1.01
41            Sabela Veloso          Galician  QA55WXDLC7SRH97X                                                                                                                                                                                                                                                                               Duis commodo orci ut dolor iaculis facilisis. Suspendisse potenti. Cras dictum dolor lacinia lectus vehicula rutrum.     7.32

In [192]:
# show specific data by language
language_uyghur = df_json[df_json["language"] == "Uyghur"]
language_uyghur.head(5)

,name,language,id,bio,version
3,Abla Dilmurat,Uyghur,5ZVOEPMJUI4MB4EN,Donec lobortis eleifend condimentum. Morbi ac ...,2.53
4,Adil Eli,Uyghur,6VTI8X6LL0MMPJCC,"Vivamus id faucibus velit, id posuere leo. Mor...",6.49
5,Adile Qadir,Uyghur,F2KEU5L7EHYSYFTT,Duis commodo orci ut dolor iaculis facilisis. ...,1.90
6,Abdukerim Ibrahim,Uyghur,LO6DVTZLRK68528I,"Vivamus id faucibus velit, id posuere leo. Nun...",5.90
11,Aygul Mutellip,Uyghur,FTSNV411G5MKLPDT,Duis commodo orci ut dolor iaculis facilisis. ...,9.10

In [ ]:
# number of data (uyghur language)
print(f"DataFrame size = {language_uyghur.shape}")
print(f"Number of Uyghur language users = {language_uyghur.shape[0]}")

DataFrame size = (20, 5)
number of Uyghur language users = 20

In [193]:
# show specific data by version
above_nine = df_json[df_json["version"] > 9.0]
above_nine.head(5)

,name,language,id,bio,version
7,Adil Abro,Sindhi,LJRIULRNJFCNZJAJ,"Etiam malesuada blandit erat, nec ultricies le...",9.32
11,Aygul Mutellip,Uyghur,FTSNV411G5MKLPDT,Duis commodo orci ut dolor iaculis facilisis. ...,9.10
23,Doreen Bartolo,Maltese,59QSX02O2XOZGRLH,Vestibulum ante ipsum primis in faucibus orci ...,9.31
26,John Falzon,Maltese,U3AWXHDTSU0H82SL,Sed nec suscipit ligula. Nullam sodales conval...,9.96
44,Philip Camilleri,Maltese,FCO0URUHARX5FDFW,Quisque efficitur vel sapien ut imperdiet. Sus...,9.97

In [197]:
# number of data (version)
print(f"DataFrame size {above_nine.shape}")
print(f"Version above 9.0 = {above_nine.shape[0]}")

DataFrame size (24, 5)
Version above 9.0 = 24